Fix using variable compilation errors in test files
Fixed compilation errors where NativeArray variables declared with
'using' statements couldn't have their members modified. Changed from:

  using (var array = new NativeArray<T>(...))
  {
      array[0] = value;  // Error: cannot modify using variable
  }

To:

  var array = new NativeArray<T>(...);
  array[0] = value;  // OK
  array.Dispose();

Fixes:
- IndexedMeshGeneratorTests.cs: NativeArray version test
- LatheGeneratorTests.cs: NativeArray version test
- ExtrusionGeneratorTests.cs: NativeArray version test